import Navbar from "@/components/Navbar/Navbar"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import "./globals.css"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <body >
          <Navbar />
          {children}
        </body>
      </html>
    </>
  )
}
